version: 2
jobs:
  build:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout
      - run:
          name: InstallDeps
          command: |
            apt update
            apt-get install -y python3 python3-venv git cmake ninja-build g++ python3-dev llvm
            python3 -m venv env
      - run:
          name: DownloadPyTorch
          command: |
            git clone https://github.com/pytorch/pytorch.git --recursive
      - run:
          name: BuildPyTorch 
          command: |
            source env/bin/activate
            cd pytorch
            pip install -r requirements.txt
            python setup.py install
            cd ..
      - run:
          name: Test 
          command: |
            source env/bin/activate
            cd tvm
            git fetch origin master:diff
            git checkout diff

            python setup.py install --cmake
            mkdir -p tvm/build/
            cp build/tvm/* tvm/build/
            cd tvm/python && python setup.py install
            cd ../..
            cd tvm/topi/python && python setup.py install
            cd ../../..

            python setup.py test 



