version: 2
jobs:
  build:
    docker:
      - image: ubuntu:latest
    resource_class: 2xlarge+
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            apt update
            apt-get install -y python3 python3-venv git cmake ninja-build g++ python3-dev llvm
            python3 -m venv env
      - run:
          name: Checkout PyTorch
          command: |
            git clone https://github.com/pytorch/pytorch.git --recursive
      - run:
          name: Build PyTorch 
          command: |
            source env/bin/activate
            cd pytorch
            pip install -r requirements.txt
            python setup.py install
            cd ..
      - run:
          name: Build and test pytorch/tvm
          command: |
            source env/bin/activate
            cd tvm
            git submodule init
            git submodule update --remote

            python setup.py install --cmake
            mkdir -p tvm/build/
            cp build/tvm/* tvm/build/
            cd tvm/python && python setup.py install
            cd ../..
            cd tvm/topi/python && python setup.py install
            cd ../../..

            python setup.py test 



